# pyproject.toml
# silence warning: legacy setup.py bdist_wheel mechanism
# see https://github.com/pypa/pip/issues/6334

[build-system]
requires = ["setuptools >= 42.0.0"]
build-backend = "setuptools.build_meta"
